repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: check-docstring-first
    -   id: debug-statements

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort

-   repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-docstrings]

-   repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
    -   id: black

-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.54.0
    hooks:
    -   id: eslint
        files: \.(js|jsx|ts|tsx)$
        types: [file]
        additional_dependencies:
        -   eslint@8.54.0
        -   eslint-plugin-react@7.33.2
        -   eslint-plugin-react-hooks@4.6.0
        -   eslint-plugin-import@2.29.0
        -   eslint-plugin-jsx-a11y@6.8.0
        -   @typescript-eslint/eslint-plugin@6.11.0
        -   @typescript-eslint/parser@6.11.0 