name: Backend CI

on:
  push:
    branches: [ main, feature/*, fix/* ]
    paths:
      - 'backend/**'
      - 'requirements.txt'
      - '.github/workflows/backend.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/**'
      - 'requirements.txt'
      - '.github/workflows/backend.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest ruff black
    
    - name: Lint with ruff
      run: |
        ruff backend
    
    - name: Format check with black
      run: |
        black --check backend
    
    - name: Test with pytest
      run: |
        cd backend
        pytest -q 